classDiagram
    class ElectricFillingStationNetwork {
        +main()
    }

    class AccountManager {
        accounts: Account [*]
        +createAccount()
        +readAccount()
        +updateAccount()
        +deleteAccount()
    }

    class CreditManager {
        +topUpCredit()
        +readCredit()
    }

    class LocationManager {
        locations: Location [*]
        +createLocation()
        +updateLocationPricing()
        +updateLocationAddress()
        +deleteLocation()
        +monitorLocationNetwork()
    }

    class ChargingPointManager {
        chargingPoints: ChargingPoint [*]
        +createChargingPoint()
        +updateChargingPoint()
        +deleteChargingPoint()
    }

    class ChargingSessionManager {
        chargingSessions: ChargingSession [*]
        +createChargingSession()
        +readChargingSession()
    }

    class InvoiceManager {
        invoices: Invoice [*]
        +createInvoiceFromSession(ChargingSession)
        +readInvoice
    }

    class Account {
        customerID: string
        name: string
        email: string
        password: string
    }

    class Credit {
        creditHistroy: Credit [*]
        amount: double
        lastUpdated: string
    }

    class Location {
        locationID: string
        address: string
    }

    class ChargingPoint {
        chargingPointID: string
        operatingStatus: OperatingStatus
    }

    class ChargingSession {
        sessionID: string
        startTime: string
        duration: integer
        chargingMode: ChargingMode
        chargingPointID: string
        energyUsed: double
        price: double
    }

    class Invoice {
        invoiceItemNumber: string
        session: ChargingSession
        account: Account
    }

    class OperatingStatus {
        <<enumeration>>
        InOperationFree
        Occupied
        OutOfOrder
    }

    class ChargingMode {
        <<enumeration>>
        AC
        DC
    }

%% System Aggregation
    ElectricFillingStationNetwork "1" *--> "1" AccountManager
    ElectricFillingStationNetwork "1" *--> "1" CreditManager
    ElectricFillingStationNetwork "1" *--> "1" LocationManager
    ElectricFillingStationNetwork "1" *--> "1" ChargingPointManager
    ElectricFillingStationNetwork "1" *--> "1" ChargingSessionManager
    ElectricFillingStationNetwork "1" *--> "1" InvoiceManager

%% Manager to Entity
    CreditManager "1" *--> "*" Credit
    AccountManager "1" *--> "*" Account
    LocationManager "1" *--> "*" Location
    ChargingPointManager "1" *--> "*" ChargingPoint
    ChargingSessionManager "1" *--> "*" ChargingSession
    InvoiceManager "1" *--> "*" Invoice
%% Domain Relationships
    Account "1" *--> "1" Credit
    Location "1" *--> "0..*" ChargingPoint
    ChargingPoint "1" --> "0..*" ChargingSession
    Account "1" --> "0..*" ChargingSession
    ChargingSession "1" --> "1" Invoice
    Account "1" -- "0..*" Invoice
